### ISSUE TITLE
Access Token

### ISSUE THREAD

**Issue by asadijabar** [chabokpush/chabok-php-demo#1]
@behrad  jan
I cannot find **access_token** (which is required in the client script) in chabok panel .

**Comment by behrad** [comment]
You can find your access_token in settings menu, in `تنظیمات وب‌سرویس` section under `Rest API Key` field

<img width="1260" alt="screen shot 1396-08-23 at 13 35 32" src="https://user-images.githubusercontent.com/2151889/32774251-f369bd38-c940-11e7-9d90-77a3de000c79.png">

**Comment by behrad** [comment]
@Husseinhj please consider renaming/addressing that REST API KEY is same as access_token
