### ISSUE TITLE
مشکل نمایش متن نوتیفیکیشن

### ISSUE THREAD

**Issue by amiriun** [chabokpush/chabok-php-demo#10]
سلام
زمانی که اپلیکیشن ( هم اندروید و هم آی او اس ) باز هست و نوتیفیکیشن ارسال می شود متن نوتیفیکیشن به درستی نمایش داده میشود ولی زمانی که اپلیکیشن ها را از رم خارج می کنیم متن نوتیفیکیشن دریافتی "پیام جدید از چابک" هست

**Comment by Husseinhj** [comment]
متد [push/toUsers](https://api.doc.chabokpush.com/#/push/push_toUsers)
دارای دو کلید `useAsAlert` و `alertText` هست
``` json
{
  "user": "string",
  "channel": "string",
  "content": "string",
  "data": {},
  "trackId": "string",
  "inApp": false,
  "live": false,
  "useAsAlert": false,
  "alertText": "string",
  "ttl": 0,
  "fallback": {},
  "clientId": "string",
  "notification": {},
  "idr": true,
  "silent": true,
  "contentBinary": "string",
  "contentType": "string",
  "id": 0
}
```
اگر `useAsAlert` رو true مقداردهی کنید، متن body را با متن cloud messaging یکسان میکنه
اگر `alertText` رو مقداردهی کنید، میتونین عنوان دلخواه بهش بدین

در پنل هم در بخش **تنظیمات**، **تنظیمات نوتیفیکیشن‌ پیام‌های چابک** متن پیام cloud messaging را برای شما مقدار دهی می‌کند که در ارسال مستقیم از پنل پیام متناسب نمایش دهید
