### ISSUE TITLE
سوال درباره ی وب هوک

### ISSUE THREAD

**Issue by amiriun** [chabokpush/chabok-php-demo#11]
سلام
وقت بخیر
میخواستم بدونم کاربرد وب هوک در تنظیمات پنل چیست؟
![screenshot-2018-1-2 adp - mobile notification messaging system](https://user-images.githubusercontent.com/5228893/34488409-aac67688-efed-11e7-92e5-67a00396f40b.png)

**Comment by Husseinhj** [comment]
وب هوک‌ها به شما کمک می‌کنن که از رویدادها باخبر بشین
بعنوان مثال، چابک رویدادهای مختلفی دارد و می‌خواهید با رخ داد یک رویدادی، کار خاصی سمت سرور خود انجام دهید.
اگر با وب هوک‌ها آشنایی ندارید شاید ساده‌ترین و کاربردی‌ترین مثال وب هوک‌ها گیت لب یا گیت هاب هستن که با تغییرات رو ریپو شما را باخبر می‌کنن.

> [Github webhooks help](https://developer.github.com/webhooks/)

شما آدرس سرویس خودتون رو در بخش تنظیمات همانند عکس بالا، وارد می‌کنین و چابک به شما رویدادهای مربوط به هر بخش رو به شما میده
این رویدادها میتونن دلیوری‌ها، آنلاین و آفلاین شدن کاربر، بازکردن برنامه و ... که در صورت نیاز به رویداد خاص با ما درمیان بذارید تا رویداد مورد نظر رو براتون فعال کنیم

**Comment by amiriun** [comment]
با تشکر از پاسختون
چه دلایلی میتونه باعث دلیور نشدن یک نوتیفیکیشن بشه؟
آیا دلیل آن هم در هوک برای ما ارسال میشه؟
آیا در صورت دلیور نشدن یک نوتیفیکیشن ، پس از هوک شدن ، ارسال مجدد در همان لحظه را پیشنهاد میکنید؟
ممنون

**Comment by behrad** [comment]
> چه دلایلی میتونه باعث دلیور نشدن یک نوتیفیکیشن بشه؟

عمدتن مسائل شبکه یا خرابی‌های سمت کلاینت باعث این اتفاق میشه



> آیا دلیل آن هم در هوک برای ما ارسال میشه؟

نخیر، این کار منطق ندارد. دلیور نشدن رو شما چطور تعریف میکنید؟ تا کی نرسه میگید دلیور نشده؟
بنابراین برای دلیور نشدن هوکی برای شما نمیاد



> آیا در صورت دلیور نشدن یک نوتیفیکیشن ، پس از هوک شدن ، ارسال مجدد در همان لحظه را پیشنهاد میکنید؟

مدیریت ارسال مجدد و رسوندن پیام بر عهده چابک می باشد نه شما

**Comment by amiriun** [comment]
سلام
ما نیاز داریم که رویدادی تحت عنوان 
register
اضافه شود که زمانی که کاربر توسط چابک رجیستر شد به ما اطلاع داده شود

**Comment by behrad** [comment]
با اجازتون یک ایشوی جدید زدم که به طور مجزا وجود داشته باشه و قابل پیگیری و سرچ باشه
https://github.com/chabokpush/chabok-php-demo/issues/20
