### ISSUE TITLE
حداکثر تعداد گیرندگان یک نوتیفیکیشن

### ISSUE THREAD

**Issue by amiriun** [chabokpush/chabok-php-demo#12]
سلام
در هر نوتیفیکیشن ارسالی حداکثر تعداد دریافت کنندگان نوتفیکیشن چند نفر می تواند باشد؟
آیا تعداد گیرندگان یک نوتیفیکیشن در response time تغییری ایجاد میکند؟

**Comment by behrad** [comment]
حداکثر دریافت کنندگان، طبیعتن تعداد گوشی‌های نصب شده روی چابک هست
و این موضوع تاثیر محسوسی روی زمان پاسخ ندارد.
