### ISSUE TITLE
reject شدن نوتیفیکیشن

### ISSUE THREAD

**Issue by amiriun** [chabokpush/chabok-php-demo#13]
سلام
وقت بخیر
آیا پس از دلیور نشدن یک نوتیفیکیشن ، چابک علاوه بر ارسال هوک اطلاع رسانی به فرستنده ، تلاش مجددی برای ارسال نوتیفیکیشن به گیرنده انجام میدهد؟

**Comment by behrad** [comment]
نوتیفیکیشن سمت سرور‌های ابری، توسط خود اون ‌ها مجددن تلاش میشن که به گوشی برسن (اگه گوشی آنلاین نباشه الان)
و نوتیفیکیشن حاصل از پیام چابک، توسط خود چابک تلاش مجدد میشه

در حالت دلیور نشده، هیچ اطلاع رسانی به فرستنده انجام نمیشود چون اینکار منطقی نیست.
