### ISSUE TITLE
tags

### ISSUE THREAD

**Issue by amiriun** [chabokpush/chabok-php-demo#14]
سلام 
وقت بخیر
نحوه ی اضافه و حذف تگ از یک کاربر خاص در پکیج پی اچ پی به چه شکل است؟
همچنین اگر بخواهیم از طریق پکیج پی اچ پی برای کاربران دارای یک یا چند تگ نوتیفیکیشن ارسال کنیم به چه شکل این کار انجام می شود؟

**Comment by behrad** [comment]
برای افزودن/حذف تگ به [مستندات](https://github.com/chabokpush/chabok-php-demo/blob/master/docs/Api/InstallationApi.md#installationaddtag) موجود رجوع نمایید

برای ارسال از طریق تگ هم از متد زیر استفاده کنید
https://github.com/chabokpush/chabok-php-demo/blob/master/docs/Api/PushApi.md#pushbyquery
این هم شمای ورودی این متد هستش
https://github.com/chabokpush/chabok-php-demo/blob/master/docs/Model/SegmentPush.md

که می بایست
```
target: {
  tags: ['my_tag']
}
```
باشد

مثال کامل تری رو می تونید اینجا پیدا کنید
https://api.doc.chabokpush.com/#/push/push_byQuery
