### ISSUE TITLE
ارسال نوتیفیکیشن برای یک agent خاص

### ISSUE THREAD

**Issue by amiriun** [chabokpush/chabok-php-demo#15]
سلام
وقت بخیر
در صورتی که بخوایم برای کاربری که هم دستگاه اندرویدی و هم دستگاه آی او اسی دارد  . نوتیفیکیشنی را فقط برای دستگاه اندرویدیش ارسال کنیم نحوه ی پیاده سازی آن به چه صورت است؟

**Comment by behrad** [comment]
در زمان ارسال پیام می بایست کانال رو معادل آیدی دیوایس اندرویدی قرار بدید
```
user: '98912....',
channel: '12asdsadj3k2131312kljmcnv`
```
