### ISSUE TITLE
ارتباط داخل دیتاسنتر

### ISSUE THREAD

**Issue by amiriun** [chabokpush/chabok-php-demo#16]
سلام
وقت بخیر
آیا در صورت قرارگیری سرورهای چابک در یک دیتاسنتر مشترک با سرور فرستنده ، آیا امکان برقراری ارتباط با آی پی داخلی دیتاسنتر می تواند فراهم شود؟

**Comment by behrad** [comment]
منظور شما رو از این سوال متوجه نمیشم
اما اگه منظورتون فراخوانی وب هوک شماست
باید بگم که نخیر،
وب هوک شما باید یک آدرس پابلیک داشته باشد

**Comment by amiriun** [comment]
منظور من این هست که اگر سرورهای ما در یک دیتاسنتر مشترک با سرورهای چابک باشد آیا امکان این وجود دارد که ارتباط rest بین ما با آی پی داخلی در دیتاسنتر باشد؟

**Comment by behrad** [comment]
سرور چابک کافیه شما رو ببینه و برای این نیاز هست که شما یک ای‌پی ولید داشته باشین
در واقع نیاز هست شما همونطور که وب سرویس‌های دیگتون رو ارايه میدین، یک سرویس دیگه بهش اضافه کنید

عرف انجام وب هوک هم به همین شکل هست و شرکت‌های سرورهای خودشون رو در شبکه محلی هم قرار نمی دهند.
