### ISSUE TITLE
کاور در نوتیفیکیشن

### ISSUE THREAD

**Issue by amiriun** [chabokpush/chabok-php-demo#17]
سلام
برای قراردادن تصویر در نوتیفیکیشن به چه شکل باید عمل کرد؟
ممنون

**Comment by behrad** [comment]
اگر منظورتون ریچ نوتیفیکیشن مطابق استاندارد گوگل و اپل هست، این امکان در حال حاضر بتا هست و ریلیز نشده روی چابک،
اگر برنامه‌ای روش دارید می تونید به ما بگید که تسریع ببخشیم ریلیزش رو 
اما اگر منظورتون ارسال آدرس تصویر هست شما می تونید از جیسانی که داخل پیام میگذارید استفاده کنید و در سمت کلاینت آدرس عکس رو بگیرید و ازش استفاده کنید. 
برای راه دوم، پنل چابک پشیبانی آپلود عکس و ارسال اون داخل محتوای جیسان دیتای پیام رو دارد که می توان براتون فعالش کرد

**Comment by mohammadTaghy** [comment]
سلام.
من از onesignal استفاده می کردم اما چون تحریم کرده دارم کوچ می کنم به چابک.
اما نمیفهمم چطور از .net نوتیفیکیشن بفرستم و مستندات که خوندم بیشتر گیج شدم.امکانش هست من را راهنمایی کنید؟
با سپاس

**Comment by Husseinhj** [comment]
@mohammadTaghy جان
لطفا issue
 جدید تو [ریپازیتوری دات نت](https://github.com/chabokpush/chabok-client-wp/issues) ما بزن اونجا راهنماییت می‌کنم
