### ISSUE TITLE
عنوان نوتیفیکیشن

### ISSUE THREAD

**Issue by amiriun** [chabokpush/chabok-php-demo#18]
سلام 
عنوان نوتیفیکیشن به چه شکل باید ارسال شود؟
تا جایی که من مستندات رو خوندم فقط content گرفته می شود

**Comment by behrad** [comment]
طبق [این مستند](https://github.com/chabokpush/chabok-php-demo/blob/master/docs/Model/SegmentPush.md) شما می تونید از 
alertText
برای متن نوتیفیکیشن استفاده کنید

**Comment by amiriun** [comment]
برای متن نوتیفیکیشن مشکلی وجود نداره و از کانتنت استفاده میکنیم
مشکل ما عنوان نوتیفیکیشن هست که وقتی
alertText
هم میذاریم نمایش داده نمیشه !!

**Comment by behrad** [comment]
> برای متن نوتیفیکیشن مشکلی وجود نداره و از کانتنت استفاده میکنیم
> مشکل ما عنوان نوتیفیکیشن هست که وقتی
> alertText
> هم میذاریم نمایش داده نمیشه !!

عذر میخوام من منظورتون رو متوجه نشده بودم.
برای عنوان نوتیفیکیشن می تونید از کلید 
‍`notification`
.در همون درخواست استفاده کنید

بعنوان نمونه:
```
content: 'My Main Text',
..
notification: {
  title: 'My Title',
  body: 'My Body'
}
```

**Comment by amiriun** [comment]
تفاوت
My Main Text و My Body
تو چیه؟

**Comment by behrad** [comment]
`My Main Text`
محتوای اصلی پیام شماست.
اما ممکن هست نخواین اون رو در داخل نوتیفیکیشنی که برای اون پیام نمایش داده میشه نشون بدید
برای همین می تونید از متن
`My Body`
استفاده کنید.

اکر
`My Body`
رو نزارید چابک برای متن داخل نوتیفیکیشن خودش تصمیم می گیره به این شکل که
اگه
`useAsAlert`
ست شده باشه، از همون متن اصلی پیام شما استفاده میکنه 
اما اگه ست نشده باشه، از متن پیش فرض نوتیفیکیشن (که داخل پنل قابل ویرایش هست) استفاده میکنه

**Comment by amiriun** [comment]
>  محتوای اصلی پیام شماست.
اما ممکن هست نخواین اون رو در داخل نوتیفیکیشنی که برای اون پیام نمایش داده میشه نشون بدید
برای همین می تونید از متن

اگر ما نخوایم که محتوای اصلی ما داخل نوتیفیکیشن نمایش داده بشه ، چه دلیلی برای پر کردن این مورد هست؟

**Comment by behrad** [comment]
> اگر ما نخوایم که محتوای اصلی ما داخل نوتیفیکیشن نمایش داده بشه ، چه دلیلی برای پر کردن این مورد هست؟

این محتوای پیام شماست و لطفن پیام رو با نوتیفیکیشن اشتباه نگیرید.
مثال‌های زیادی هست، من دوتاش رو براتون میگم
 مورد یک تلگرام هست، فرض کنید اصل پیام من به شما یک متن طولانی هست اما تلگرام میخواد در اعلانی که روی صفحه شما میاره بنویسیه بهراد برای شما پیام ارسال کرده است
مورد دوم محتوای یک تراکنش بانکی هست، ممکنه متن کامل حاوی موجودی و ... شما باشه اما اپلیکیشن بخواد روی اعلان بیاد شما یک خرید داشتید.

شفافه ؟

**Comment by amiriun** [comment]
> فرض کنید اصل پیام من به شما یک متن طولانی هست اما تلگرام میخواد در اعلانی که روی صفحه شما میاره بنویسیه بهراد برای شما پیام ارسال کرده است

چرا باید متن طولانی محتوای ما در کنار اعلان "بهراد برای شما پیام ارسال کرده است" ارسال شود؟

> این محتوای پیام شماست و لطفن پیام رو با نوتیفیکیشن اشتباه نگیرید.

تفاوت پیام با نوتیفیکیشن چیه؟

**Comment by behrad** [comment]
> چرا باید متن طولانی محتوای ما در کنار اعلان "بهراد برای شما پیام ارسال کرده است" ارسال شود؟

آنچه باید ارسال شود محتوای طولانی شماست، اما همونطور که عرض کردم ممکن هست نخوایید همون رو داخل متن اعلان به کاربر نمایش دهید. در این صورت ارسال یک نوتیفیکیشن اضافی فقط برای این منظور مسخره به نظر می رسه



> تفاوت پیام با نوتیفیکیشن چیه؟

منظور از پیام، یک پیام (چه متنی چه غیر متنی) چابک است که به طور مستقیم بین سرور ‌های چابک و کلاینت جا به جا می شود

اما منظور از نوتیفیکیشن، سرویس پوش نوتیفیکیشن پلتفرم‌های موبایل هستش
GCM, APNs, WNS, Mozilla, ...
