### ISSUE TITLE
Push Response

### ISSUE THREAD

**Issue by amiriun** [chabokpush/chabok-php-demo#19]
سلام
وقت بخیر
زمانی که سگمنت پوش انجام میدیم و برای تعدادی کاربر پوش ارسال میکنیم در پوش ریسپانس آرایه ای حاوی 
count , id
برای هر پوش ارسال می شود
چون پوش ها انبوه ارسال می شود ما نیاز داریم بدونیم که هر کدام از پوش ریسپانس ها متعلق به کدام پوش می باشد
لذا نیاز داریم دیتای ارسالی هم در ریسپانس ها برگردانده شود

**Comment by behrad** [comment]
اگر منظورتون رو درست متوجه شده باشم:

تعداد پوش‌های ارسال شده در سگمنت می تواند خیلی زیاد باشد و حتی ارسال ممکن هست در بازه زمانی طولانی تر از چند ثانیه انجام شود
بنابراین برگرداندن تک نک آیدی‌ها در پاسخ پوش سگمنت کار منعقولی نمی‌باشد.
برای این منظور شما بعد از دریافت آیدی سگمنت از یک درخواست دیگر برای دریافت جزییات (آیدی‌ها) استفاده کنید
که در صورتی که این درخواست الان در دسترس عموم نباشد، برای شما در دسترس قرار خواهد گرفت

بنابراین بفرمایید که چه نیازی دارید تا بتونیم پاسخ اون درخواست دومی رو براتون تنظیم کنیم

**Comment by amiriun** [comment]
من فکر میکنم روشی که شما پیشنهاد دادید روش مناسبی نیست
یعنی ما برای اینکه بفهمیم کدام آرایه از پوش ریسپانس برای کدام یوزر هست یک درخواست دیگر بزنیم ممکنه خودش ۳۰هزار درخواست بشه!
یک مپینگ ساده در ریسپانس به اینکه این ریسپانس آی دی برای کدام یوزر است نیاز ما رو برآورده میکنه
فقط کافیه تو پوش ریسپانس کنار هر آی دی ، یوزر آی دی مربوطه رو هم بزارید

**Comment by behrad** [comment]
> ما نیاز داریم بدونیم که هر کدام از پوش ریسپانس ها متعلق به کدام پوش می باشد

این جمله رو برای من بیشتر توضیح میدین؟




> فقط کافیه تو پوش ریسپانس کنار هر آی دی ، یوزر آی دی مربوطه رو هم بزارید

من مطمئن نیستم منظور شما رو متوجه شده باشم.
شما وقتی یک پوش سگمنت میزنید میخواید تمام یوزر‌آیدی هایی که براش پوش رفته رو داشته باشید؟
و لطفن بفرمایید چه کاربری براتون داره تا بهتر راهنماییتون کنم

**Comment by amiriun** [comment]
ما نیاز داریم  بدونیم که **این پوش آی دی ای که شما در ریسپانس پوش سگمنت میدید مرتبط با پوش ارسال شده برای کدام یوزر در ریکوئست هست؟**

**Comment by behrad** [comment]
این آیدی، در واقع آیدی کمپین یا سگمنت شما هست که خودش شامل یک سری پوش به کاربران اون سگمنت هست
بنابراین می تونه شامل هزاران یوزر باشه.
شما که در پوش سگمنت یوزر مشخص نمی کنید.
بنابراین باید یک درخواست دیگری باشد تا بهش این آیدی که گرفتید رو بدید
اون به شما یوزر‌هایی که براشون این پوش رفته رو برگردونه

**Comment by amiriun** [comment]
اگر آی دی ای که دریافت میکنم آی دی سگمنت هست پس چرا به تعداد یوزرهاست؟
طبق تصویر زیر
![screenshot from 2018-01-17 17-52-37](https://user-images.githubusercontent.com/5228893/35047515-74232cac-fbaf-11e7-9709-c871a9a46e78.png)

**Comment by behrad** [comment]
سگمنت هیچ موقع دو تا بر نمیگردونه
فکر میکنم شما اصن از سگمنت پوش استفاده نمی کنید و احتمالن دارین یوزرپوش رو استفاده میکنید.

لطفن متدی که فراخوانی می کنید همراه نمونه ورودیش بفرمایید چی هست

می تونید ایدی برگشتی رو هم برای من کپی کنید
از تو عکس قابل استفاده نیست

**Comment by amiriun** [comment]
بله درسته pushToUsers
من فکر میکردم منظور شما از ارسال سگمنت همین هست.
حالا اینجا چجوری مشکل رو حل کنیم؟

**Comment by behrad** [comment]
> بله درسته pushToUsers

این ارسال کانال هست (شخصی و عمومی)
ارسال سگمنت از طریق متد 
‍`byQuery`
انجام میشه




> حالا اینجا چجوری مشکل رو حل کنیم؟

مشکلی وجود ندازه. شما به متد یوزر پوش، دو تا پوش ورودی دادین. برای هر کدومش به شما یک آیدی برگردونده شده
ترتیب آیدی‌های برگشتی همون ترتیب ورودی شما هست :)

**Comment by amiriun** [comment]
> ترتیب آیدی‌های برگشتی همون ترتیب ورودی شما هست

بله حرف شما درسته به این شکل هم میشه کار کرد.
حالا اگه ما بخوایم در جواب کنار آی دی های برگشتی یوزر آی دی هم باشه امکان پذیر هست؟

**Comment by behrad** [comment]
> حالا اگه ما بخوایم در جواب کنار آی دی های برگشتی یوزر آی دی هم باشه امکان پذیر هست؟

نخیر چون دلیل منطقی‌ای برای اینکار وجود ندارد.

در اکثر سرور‌هایی که همچین موردی هست، شما ایدی ها رو به ترتیب وروی دریافت می کنید بنابراین می دونید هر آیدی برای کدام یوزر هست
