### ISSUE TITLE
رویداد کاربر جدید (رجیستر) در وب هوک

### ISSUE THREAD

**Issue by behrad** [chabokpush/chabok-php-demo#20]
ما در حال حاضر رویداد‌های زیر رو داریم

1. یوزر آیدی جدید - وقتی یک یوزر‌ایدی برای اولین بار رجیستر میکند
2. نصب جدید - وقتی یک کاربر برای اولین بار روی یک گوشی جدید رجیستر میکند
3. باز شدن برنامه - وقتی کاربری برنامه رو باز میکند

که هیچ کدوم در وب هوک فعلن نمیاین.
برای هر کدوم که بخواین می تونیم وب هوک جدید تعریف کنیم @amircup2006

**Comment by amiriun** [comment]
سلام
ما نیاز به اولی داریم
یعنی زمانی که یک یوزر أی دی برای اولین بار توی چابک رجیستر میشه

**Comment by behrad** [comment]
> ما نیاز به اولی داریم

بله اضافه میشه براتون و خبر میدیم

**Comment by behrad** [comment]
در پنل چابک تنظیمات وب هوک برای ۳ رویداد جدید اضافه شده است
