### ISSUE TITLE
async requests

### ISSUE THREAD

**Issue by amiriun** [chabokpush/chabok-php-demo#21]
سلام
وقتتون بخیر
آیا این امکان وجود دارد که ریکوئست ها به صورت 
async
ارسال شوند؟

**Comment by behrad** [comment]
منظورتون کدوم ریکوئست هست؟

**Comment by amiriun** [comment]
کلا آیا داخل پکیج کانفیگی وجود داره که کل درخواست ها به صورت
async
ارسال بشه؟

**Comment by behrad** [comment]
اگر متد‌های داخل کد پی اچ پی رو می فرمایید، در حال حاضر نه متاسفانه.
اگر نیاز دارین ای‌سینک باشه، می تونید از رست کلاینت خودتون استفاده کنید جای این لایببری
