### ISSUE TITLE
ارسال نوتیفیکیشن منطقه ای

### ISSUE THREAD

**Issue by amiriun** [chabokpush/chabok-php-demo#23]
سلام
وقت بخیر
برای ارسال نوتیفیکیشن منطقه ای و همینطور دریافت لیست کاربرانی که نوتیفیکیشن برای آن ها ارسال شده کدام 
API
باید استفاده شود؟

**Comment by amir-yaghoubi** [comment]
<div dir="rtl">
سلام


> برای ارسال نوتیفیکیشن منطقه ای

با استفاده از API

</div>

`POST /push/byQuery`

<div dir="rtl">
و فراهم آوردن فیلد <b>nearBy</b> شما می‌توانید نسبت به ارسال نوتیفیکشین منطقه‌ای اقدام کنید.
برای مثال:
</div>

```JSON
{  
  "target": {
     "nearBy":  {
        "lat":  35.759659688789284,
        "lng":  51.4004909992218,
        "radius":  100 
      }
 }
}  
```
<div dir="rtl">
برای مطالعه بیشتر به این بخش از <a href="https://api.doc.chabokpush.com/#/push/push_byQuery">مستندات</a> مراجعه نمایید.



</br></br>

> دریافت لیست کاربرانی که نوتیفیکیشن برای آن ها ارسال شده

در حال حاضر API عمومی برای این قسمت نداریم. جهت دریافت اعلان تحویل نوتیفیکیشن‌های ارسال شده می‌توانید از webhook تحویل استفاده کنید.
در صورتی که مورد استفاده شما با وب‌هوک بر طرف نمی‌شود ما را مطلع نمایید.
</div>

**Comment by amiriun** [comment]
>  در صورتی که مورد استفاده شما با وب‌هوک بر طرف نمی‌شود ما را مطلع نمایید.

ما نیاز داریم که به محض ارسال شدن پوش منطقه ای مطلع بشیم که برای چه کسانی این نوتفیکیشن ارسال شده است.

**Comment by amir-yaghoubi** [comment]
<div dir='rtl'> بعد از ارسال پوش با <code>POST /push/byQuery</code> </div>
<div dir='rtl'>به شما <b>id</b> داده می‌شود که شما می‌توانید با استفاده از API <a dir='ltr' href="https://api.doc.chabokpush.com/#/message/message_listById">/messages/listById/{id}</a> لیست کسانی که نوتفیکشین برایشان ارسال شده است را بدست بیاورید.</div>

**Comment by amir-yaghoubi** [comment]
<div dir='rtl'>من این issue رو میبندم اگه مشکلتون رفع نشد دوباره باز کنین.</div>
