### ISSUE TITLE
پخش صدای پیش فرض اندروید

### ISSUE THREAD

**Issue by miladrasooli** [chabokpush/chabok-php-demo#24]
سلام برای پخش صدای پیش فرض اندروید چه مقداری باید به sound داده بشه؟

**Comment by Husseinhj** [comment]
<div dir='rtl'>در repository android سوال شما پاسخ داده شده</div>

[repository android](https://github.com/chabokpush/chabok-client-android/issues/3)

**Comment by Husseinhj** [comment]
من ایشو رو میبندم. اگر جواب سوال خودتونو پیدا نکردین، مجددا ایشو رو باز کنین و در موردش بیشتر توضیح بدین
