### ISSUE TITLE
ایرادات عجیب غریب

### ISSUE THREAD

**Issue by SajjadKharrazi** [chabokpush/chabok-php-demo#25]
سلام
به نظر میرسه سیستم پوش نوتیفیکیشن ایرادات اساسی داره
یا حداقل داکیومنت درست حسابی نشده و مشکلات عجیب غریب توش هست

<img width="927" alt="screen shot 1397-05-31 at 14 40 25" src="https://user-images.githubusercontent.com/7239983/44457817-8de83a00-a619-11e8-8445-f7a9bac0d38a.png">
طبق این عکس من دیروز کال میکردم نوتیفیکیشن میومد
الان عینا همون رو دارم کال میکنم هیچ نوتیفیکیشنی نمیاد که هیچ، اصن توی لیست پیام های پنلمم نمیره

نکته و سوال بعدی اینه که این چه ریسپانسیه که اومده؟؟ اصن یعنی چی؟؟ ۲ یعنی چی؟
اینا چرا درست حسابی داکیومنت نشده

به شکل واضح اپلیکیشن ۹۰ هم همین مشکلات رو توی ارسال نوتیفیکشن داره
بعضی وقتا میاد و بعضی وقتا که وارد اپ میشیم یهو تعداد زیادی باهم میاد که معلومه از زمانش گذشته

**Comment by behrad** [comment]
> طبق این عکس من دیروز کال میکردم نوتیفیکیشن میومد الان عینا همون رو دارم کال میکنم هیچ نوتیفیکیشنی نمیاد که هیچ، اصن توی لیست پیام های پنلمم نمیره

اگر شما بخش[ راهنمای وب سرویس‌ها](https://doc.chabokpush.com/rest-api/guide.html) رو مطالعه می‌کردید، متوجه می شدید که برای هر وب سرویس یک سری پارامتر‌ها اجباری هست
این درخواستی که شما فراخوانی می کنید هم مستنداتش [اینجا](https://api.doc.chabokpush.com/#/push/push_toUsers) هست و پارامتر‌های اجباریش با ستاره مشخص شدند

بنابراین چیزی که واضحه اینه که شما کلید 
`content`
رو ارسال نمی کنید بنابراین پیام شما معتبر نیست.


مشکل چابک در این مورد این هست که جای اینکه به شما پیام خطا برگردونه، خطای شما رو از چشم شما مخفی می کنه
که این مورد رو اصلاح خواهیم کرد
@amir-yaghoobi 


> نکته و سوال بعدی اینه که این چه ریسپانسیه که اومده؟؟ اصن یعنی چی؟؟ ۲ یعنی چی؟

اون فیلد به معنی تعداد گیرندگان این پیام هست



> اینا چرا درست حسابی داکیومنت نشده

مستندات به مرور زمان در حال بهبود و به روز شدن هست
توصیه میکنم شما هم یکم صبور باشید و از لحن مناسب تری استفاده کنید

> به شکل واضح اپلیکیشن ۹۰ هم همین مشکلات رو توی ارسال نوتیفیکشن داره
> بعضی وقتا میاد و بعضی وقتا که وارد اپ میشیم یهو تعداد زیادی باهم میاد که معلومه از زمانش گذشته

مسائل مربوط به اپ نود رو باید با آدرس ایمیل رسمی این اپلیکیشن در میون بگذارید تا بهره برداران این اپلیکیشن بررسیش کنن
چایک سرویس دهنده این اپلیکیشن هستش نه مسئول ارسال‌ها و نحوه استفاده

**Comment by SajjadKharrazi** [comment]
> رو ارسال نمی کنید بنابراین پیام شما معتبر نیست.

عین همین ریکوئست دیروز ارسال میشد و نوتیفیکیشن میرسید.
شما به تایتل نوتیفیکیشن دقت کنید از قصد کانتنت حذف شده بود برای تست، که اتفاقا نوتیفیکیشن بدون کانتنت هم ارسال میشد
بگذریم از اینکه الان حتی کانتنت هم اضافه کنیم باز تغییری حاصل نمیشه

> اون فیلد به معنی تعداد گیرندگان این پیام هست

باز هم اگه به محتوای ارسالی توجه کنید میبینید که به یک یوزر با شناسه مشخص ارسال شده پس ریسپانس کانت ۲ یقینا اشکال داره

> چایک سرویس دهنده این اپلیکیشن هستش نه مسئول ارسال‌ها و نحوه استفاده

بله موافقم با شما، اما بخش زیادیش مربوط به همین داکیومنت ها و ایرادات چابک هست

**Comment by behrad** [comment]
> عین همین ریکوئست دیروز ارسال میشد و نوتیفیکیشن میرسید.
> شما به تایتل نوتیفیکیشن دقت کنید از قصد کانتنت حذف شده بود برای تست، که اتفاقا نوتیفیکیشن بدون کانتنت هم ارسال میشد
> بگذریم از اینکه الان حتی کانتنت هم اضافه کنیم باز تغییری حاصل نمیشه

همواره پیام بدون کلید کانتنت ارسال نمیشده و نمیشه
به درخواست‌های دیروزتون دقت کنید و با توجه به اینکه میفرمایید رسیدن، از توی پنل تون برامون لاگ پیام‌ها رو بفرستید تا باهم اینجا بررسی کنیم



> باز هم اگه به محتوای ارسالی توجه کنید میبینید که به یک یوزر با شناسه مشخص ارسال شده پس ریسپانس کانت ۲ یقینا اشکال داره

یک شماره می تونه با دو دستگاه روی چابک رجیستر شده باشه



> بله موافقم با شما، اما بخش زیادیش مربوط به همین داکیومنت ها و ایرادات چابک هست

شما همین مستندات موجود رو هم با دقت بیشتری مطالعه کنید خیلی بهتر می تونید از چابک استفاده کنید
اگر هم فکر میکنید با مفاهیم اولیه چابک مشکل دارید می تونید درخواست جلسه دموی رایگان بدید



> بگذریم از اینکه الان حتی کانتنت هم اضافه کنیم باز تغییری حاصل نمیشه

یکم با دقت بیشتری پنل و وب سرویس رو استقاده کنید و اگه موفق نشدید ارسال کنید جزییات خطا یا مشکل تون رو بگذارید اینجا تا کمک تون کنیم

**Comment by SajjadKharrazi** [comment]
> یک شماره می تونه با دو دستگاه روی چابک رجیستر شده باشه

متاسفانه یا خوشبختانه فقط یه دونه دستگاه رجیستر کردم 
![image](https://user-images.githubusercontent.com/7239983/44462737-d8be7d80-a62a-11e8-958c-ac7d6a95ea6d.png)

> اگر هم فکر میکنید با مفاهیم اولیه چابک مشکل دارید می تونید درخواست جلسه دموی رایگان بدید

به نظرم باید انقدی همه چیز کامل و واضح باشه که کار به جلسه دموی رایگان نرسه
اولین و مهمترین سرویسی که باید ارائه بشه همین داکیومنت هاس نه جلسه دموی رایگان

**Comment by behrad** [comment]
> متاسفانه یا خوشبختانه فقط یه دونه دستگاه رجیستر کردم

آیدی پنل تون رو برای ما تو ایمیل ارسال کنید تا چک کنیم این مورد رو و دلیلش رو بهتون بگیم



> به نظرم باید انقدی همه چیز کامل و واضح باشه که کار به جلسه دموی رایگان نرسه
> اولین و مهمترین سرویسی که باید ارائه بشه همین داکیومنت هاس نه جلسه دموی رایگان

ما برای بهتر و کامل تر شدن مستندات مون داریم تلاش میکنیم و به اهمیتش بسیار واقفیم

اما پلتفرم‌هایی که سازمانی و بزرگ هستند انقدر پیچیده هستند که صرفن با مطالعه مستندات نمیشه به طور کامل بهترین بازدهی رو ازشون داشت
اگر تجربه استفاده از پلتفرم‌های مشابه خارجی رو داشته باشید، اون‌ها همینطور هستند و طی یک فرآیند تجاری به بهره برداری می رسند نه صرفن مطالعه مستندات
در خیلی از موارد حتی تریک‌های استفاده و یک سری مفاهیم رو داخل مستندات عمومی شون نمیگذارند، حداقل این چیزیه که شما به تجربه باهاشون متوجه میشید.

به هر حال، چیزی که الان به چابک کمک میکنه این هست که هر موردی یا سوالی هست برای ما ارسال بشه تا بهبود بدیم و مستندات رو به روز تر کنیم
بقیه بحث فکر نمی‌کنم توش نکته‌ای باشه

**Comment by SajjadKharrazi** [comment]
> همواره پیام بدون کلید کانتنت ارسال نمیشده و نمیشه

<img width="991" alt="screen shot 1397-06-05 at 17 24 14" src="https://user-images.githubusercontent.com/7239983/44660880-39302f00-aa1e-11e8-872c-bdc8b212aa22.png">

![img_3506](https://user-images.githubusercontent.com/7239983/44660887-43522d80-aa1e-11e8-8c2e-f7918128072a.PNG)

بنظرم یه بازنگری اساسی توی سرویس ها و ای پی آی هاتون بکنید
همونطور که گفتم مشکلات زیاده متاسفانه

**Comment by behrad** [comment]
این موضوع رو بررسی کردیم
وجود کلید کانتنت برای ارسال و دریافت پیام چابک اجباریه

اما ای‌پی‌آی چابک خطا به شما نمی‌ده و البته یک نوتیفییکیشن برای شما ارسال می کنه (چون کلیدش رو گذاشته اید) و توجه داشته باشید که پیام چابک با نوتیفیکیشن فرق میکنه



> بنظرم یه بازنگری اساسی توی سرویس ها و ای پی آی هاتون بکنید
> همونطور که گفتم مشکلات زیاده متاسفانه

این ای‌پی‌آی ها مطابق مستندات و آموزش داره در طول روز توسط ده‌ها اپلیکیشن فراخوانی و استفاده میشه
مشکلاتی رو که می فرمایید به طور مشخص و دقیق براشون ایشو بزنید اگه نیاز به بازنگری داشت حتمن انجام میدیم :)


این موضوع به نظرم شفاف شده دیگه و ایشو تکلیفش روشنه. ایشو رو می بندم اگه سوالی داشتید بپرسید
