### ISSUE TITLE
ارسال data با push

### ISSUE THREAD

**Issue by Mr-Hqq** [chabokpush/chabok-php-demo#26]
سلام
با push محتوای غیر متنی ارسال نمیشه 
هم با Rest چک کردم و هم از پنل

**Comment by Husseinhj** [comment]
<div dir='rtl'><code>Response</code> که از<code>Rest</code> دریافت می‌کنین چی هست؟ 
</br>
و اگر امکانش هست<code>body</code> پوش رو هم اینجا قرار بدید
</div>

**Comment by Mr-Hqq** [comment]
هیچ مشکلی تو ارسال نداره 
`[
    {
        "id": "hHHd57LOTgeyiOVdX_epnQ-33393",
        "count": 1
    }
]`
یه مشکل هست که اونم اینه که جز body می خوام data هم همراهش ارسال کنم اما نمیشه متاسفانه

**Comment by amir-yaghoubi** [comment]
لطفا نمونه‌ای از پوش ارسالی خودتون رو اینجا قرار بدین تا بیشتر راهنمایی کنیم.

**Comment by Mr-Hqq** [comment]
request Post : `https://sandbox.push.adpdigital.com/api/push/toUsers?access_token=xxxx`

formData: 

```js
{
application:doajibuv
channel:default
content:این یک پیام تستی است. در تاریخ: دوشنبه ۵م شهریور ۱۳۹۷ ساعت: ۱۰:۴۰:۱۵ ق.ظ
inApp:false
live:false
persist:true
silent:false
stateful:false
useAsAler:true
user:23123
data:{"wefef": "wefwefwef"}
}
```

output in Client: 

```js
{
alertText:null
alertTitle:null
body:"این یک پیام تستی است. در تاریخ: دوشنبه ۵م شهریور ۱۳۹۷ ساعت: ۱۰:۴۰:۱۵ ق.ظ"
channel:"23123/default"
createdAt:1535350942703
expireAt:0
id:"hHHd57LOTgeyiOVdX_epnQ-33714"
intentType:"com.adpdigital.push.client.MSGRECEIVE"
receivedAt:1535350942945
senderId:null
sentId:null
sound:null
}
```

output Rest: 
```js
[
    {
        "id": "HILxPyFnRvScneEViBu1gg-34399",
        "count": 1
    }
]
```

خروجی کلاینت هیچ داده ای با نام data نداره

**Comment by amir-yaghoubi** [comment]
<div dir="rtl">
من توی نمونه‌ی شما <code>data</code>ای نمی‌بینم.
این نمونه‌ای از ارسال پیام همراه دیتا هستش:
<pre dir="ltr">
{
"application": "doajibuv",
"channel":"default",
"content":"این یک پیام تستی است.↵در تاریخ: دوشنبه ۵م شهریور ۱۳۹۷↵ساعت: ۱۱:۰۴:۰۸ ق.ظ",
"data": { // please put your custom data in here.
   "sample": true
 },
"persist": true,
"silent": false,
"stateful": false,
"useAsAlert": true,
"user":"<-userId->"
}
</pre>
</div>

**Comment by Mr-Hqq** [comment]
<div dir="rtl">
ارسال با json درست شد اما هنوز data ارسال نمیشه
</div>

**Comment by amir-yaghoubi** [comment]
<div dir="rtl">
توی بررسی‌های که ما انجام دادیم مقدار <code>data</code> ارسال میشن.

این هم یک نمونه از <code>curl</code> (مقدار access_token و user رو مقدار مناسب قرار بدین)

<pre dir="ltr">
curl -X POST "https://sandbox.push.adpdigital.com/api/push/toUsers?access_token=xxxxxx" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"channel\":\"default\",\"content\":\"این یک پیام تستی است.↵در تاریخ: دوشنبه ۵م شهریور ۱۳۹۷↵ساعت: ۱۱:۰۴:۰۸ ق.ظ\",\"data\": { \"sample\": true },\"persist\": true,\"silent\": false,\"stateful\": false,\"useAsAlert\": true,\"user\":\"xxxx\"}"
</pre>

توجه داشته باشید که header شما مقدار <code>application/json</code> باشد.
</div>

**Comment by Mr-Hqq** [comment]
<div dir="rtl">من از react native به عنوان کلاینت دارم استفاده می کنم. نمی دونم چرا  اما curl هم data رو ارسال نمی کنه</div>

**Comment by amir-yaghoubi** [comment]
<div dir="rtl">
لطفا از طریق پنل کاربری خودتون بخش پیام‌ها، پیام ارسال شده توسط خودتون رو بررسی کنین که محتویات غیرمتنی شما ارسال شده یا نه. و این که شما روی چه دستگاهی دریافت میکنین
</div>

**Comment by Mr-Hqq** [comment]
<div dir="rtl">بله ارسال شده. اما تو خروجی های کلاینتم نمیاد. احتمالا مشکل از کلاینت بندست.ممنون</div>

**Comment by amir-yaghoubi** [comment]
<div dir=rtl>
مشکل بر روی wrapper rn ما هست که به درستی مقدار data رو parse نمیکنه و در حال برطرف کردن این مشکل هستیم.
</br>
ممنون به خاطر گزارش این باگ
</div>

**Comment by amir-yaghoubi** [comment]
<div dir=rtl>
issue مرتبط با این مشکل در <a href="https://github.com/chabokpush/chabok-client-rn/issues/6">این قسمت</a> ایجاد شد و میتونین این مشکل را در issue ایجاد شده پیگیری نمایید.
</div>
