### ISSUE TITLE
push_byQuery مشکل در ارسال با 

### ISSUE THREAD

**Issue by mehdi-mashayekhi** [chabokpush/chabok-php-demo#27]
<p dir="rtl">سلام وقت بخیر</p>
<p dir="rtl"><a href="https://api.doc.chabokpush.com/#/push/push_byQuery">https://api.doc.chabokpush.com/#/push/push_byQuery</a></p>
<p dir="rtl">در این آدرس زمانی که میخوام از <code>push_byQuery</code> استفاده کنم ارسال انجام نمیشه ، من یک کاربر با تگ  <code>user_2</code> دارم</p>
<p dir="rtl">و با این کد تست میگیرم ::</p>
<pre><code class="language-json">{
  &quot;target&quot;: {
    &quot;and&quot;: [
      {
        &quot;tags&quot;: [
          &quot;user_2&quot;
        ]
      }
    ]
  },
  &quot;notification&quot;: {
    &quot;title&quot;: &quot;chabok test&quot;,
    &quot;body&quot;: &quot;this message sent by chabok.io&quot;,
    &quot;sound&quot;: &quot;awesome.mp3&quot;
  },
  &quot;content&quot;: &quot;string&quot;
}</code></pre>
<p dir="rtl">نتیجه =</p>
<pre><code class="language-json">{
  &quot;count&quot;: 0,
  &quot;id&quot;: &quot;rD0rv2ilRyCCnQWjy6MQbg-15834&quot;
}</code></pre>
<p dir="rtl">نتیجه ای که بر میگرده میگه تعداد کاربران 0 هست و عملیات موفق چرا کاربر را نمیتونه پیدا کنه ؟</p>
<p dir="rtl">مشکل در دریافت وب پوش دارم و از وب پوش استفاده میکنم</p>

**Comment by behrad** [comment]
شکل درست پارامتر‌ها شبیه زیر است
``` js

{ 
  "target": { "and": [ { "tags": "user_2" } ] }, 
  "notification": { "title": "chabok test", "body": "this message sent by chabok.io", "sound": "awesome.mp3" }, 
  "content": "string" 
}

```

**Comment by behrad** [comment]
مورد تگ در مثالی که در مستندات وب سرویس هست اشتباه هستش 
اصلاحش میکنیم @amir-yaghoobi

**Comment by mehdi-mashayekhi** [comment]
ممنون مشکل برطرف شد ، یه سوال دیگه از کجا بفهمم شرط ها به چه شکل هست در ارسال کوئری 
مثلا الان اینجا 
and 
آورده شده من بخوام بگم اگر تگ نبود
hastag
براشون پیام ارسال کن به چه شکل میشه؟
اصلا مستندات کامل رو از کجا میتونم پیدا کنم در این خصوص کار ما شده مدام پیام دادن و واقعا بخش مستندات ضعف داره

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">بله مستندات هنوز به پختگی لازم نرسیده و ارسال پوش‌های پیچیده‌تر بزودی مستند خواهند شد.</p>
<p dir="rtl">برای ارسال پوش با شروط پیچیده‌تر شما میتونین از سگمنت‌ها استفاده کنین، برای نمونه:</p>


```
{  

   "channel":"default",
   "persist":true,
   "content":"sample_push",
   "segment":{  
      "all":[  
         {  
            "name":"tags",
            "operator":"not_include",
            "value":[ "tag_1" ]
         }
      ]
   },
   "notification":{  
      "title":"chabok test",
      "body":"this message sent by chabok.io",
      "sound":"awesome.mp3"
   }

}
```

<blockquote dir="rtl">
<p dir="rtl">توجه داشته باشید که جهت استفاده از شروط به سبک <strong>segment</strong> شروط درون فیلد <code>segment</code> به جای <code>target</code> قرار میگیرند</p>
</blockquote>
<p dir="rtl">مثال بالا پوش را برای کاربرانی ارسال میکند که تگ <code>tag_1</code> را ندارند.</p>

**Comment by amir-yaghoubi** [comment]
<h2 id="-api" dir="rtl">نحوه استفاده از سگمنت‌ها در API</h2>
<p dir="rtl">هر سگمنت می‌تواند شامل یک یا چند شرط (<code>rule</code>) باشد.</p>
<h3 id="-" dir="rtl">شرط‌ها</h3>
<p dir="rtl">هر شرط شامل ۳ قسمت اصلی می‌باشد:</p>
<ul dir="rtl">
<li dir="rtl"><code>name</code> نام فیلد</li>
<li dir="rtl"><code>operator</code> نوع عملوند (مانند بزرگتر، مساوی‌با و غیره)</li>
<li dir="rtl"><code>value</code> مقداری که سنجش می‌شود</li>
</ul>
<h3 id="-operators-" dir="rtl">عملوند‌های مجاز (operators)</h3>
<ul dir="rtl">
<li><code>equal_to</code></li>
<li><code>not_equal</code></li>
<li><code>lesser_than</code></li>
<li><code>lesser_equals</code></li>
<li><code>greater_than</code></li>
<li><code>greater_equals</code></li>
<li><code>include</code></li>
<li><code>not_include</code></li>
<li dir="rtl"><code>before</code></li>
<li dir="rtl"><code>after</code></li>
</ul>

<blockquote dir="rtl">
<p dir="rtl">عملوند‌های <code>before</code> و <code>after</code> مخصوص فیلد‌هایی از جنس زمان هستند، و مقداری که در قسمت <code>value</code> این نوع شرط‌ها قرار میگیرد به صورت <code>xh</code> می‌باشد، نمونه: <code dir="ltr">value: '6h'</code></p>
</blockquote>


<h3 id="name-" dir="rtl">name های مجاز</h3>
<ul dir="rtl">
<li dir="rtl"><code>installDate</code> زمان اولین بازدید</li>
<li dir="rtl"><code>launchTime</code> زمان آخرین بازدید</li>
<li dir="rtl"><code>launchCount</code> تعداد بازدید</li>
<li dir="rtl"><code>tags</code> تگ‌های کاربر</li>
<li dir="rtl"><code>deviceType</code> نوع دستگاه</li>
<li dir="rtl"><code>clientVersion</code> نسخه برنامه</li>
<li dir="rtl"><code>osVersion</code> نسخه سیستم‌عامل</li>
</ul>

---
<h3 id="-" dir="rtl">نمونه</h3>

```
"segment": {
  "all": [
    {
       "name": "installDate",
       "operator": "after",
       "value": "6h"
    },
    {
       "name": "launchCount",
       "operator": "greater_than",
       "value": 2
    }
  ]
}
```
<p dir="rtl">مثال بالا کاربرانی را هدف قرار می‌دهد که بعد از ۶ساعت پیش برنامه‌ را نصب کرده‌اند و بیش از ۲ بار هم آن را باز نموده‌اند.</p>

**Comment by mehdi-mashayekhi** [comment]
پاسخ عالی بود ممنون ، لطفا مستندات را در اولویت قرار بدید تکمیلش رو

**Comment by amir-yaghoubi** [comment]
این قسمت نیز به [مستندات](https://doc.chabokpush.com/rest-api/send-push.html#%D9%86%D8%AD%D9%88%D9%87-%D8%A7%D8%B3%D8%AA%D9%81%D8%A7%D8%AF%D9%87-%D8%A7%D8%B2-%D8%B3%DA%AF%D9%85%D9%86%D8%AA%D9%87%D8%A7-%D8%AF%D8%B1-api) اضافه شد

**Comment by mehdi-mashayekhi** [comment]
سلام
یک سوال دیگه ، چطور میشه از شرط های (یا) و (و) استفاده کرد
مثلا میخوایم کاربرانی که تگ 
example
یا 
example2
یا
example3

دارند ارسال بشه براشون

یا کاربرانی که 2 تگ را داشته باشند و یک تگ را نداشته باشند اینطور موارد شرطی

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">سلام،</p>
<blockquote dir="rtl">
<p dir="rtl">کاربرانی که تگ example یا example2 یا example3</p>
</blockquote>


```javascript
{
"name": "tags",
"operator": "include",
"value": ["example", "example2", "example3"]
}
```

<blockquote dir="rtl">
<p dir="rtl">یا کاربرانی که 2 تگ را داشته باشند و یک تگ را نداشته باشند اینطور موارد شرطی</p>
</blockquote>


```javascript
"segment": {
  "all": [
    {
      "name": "tags",
      "operator": "include",
      "value": ["tag1", "tag2"]
    },
    {
      "name": "tags",
      "operator": "not_include",
      "value": ["tag3"]
    }
  ]
}
```

<p dir="rtl">سگمنت بالا برای کاربرانی ارسال می‌کند که یکی از تگ‌های <code>tag1</code> و <code>tag2</code> را دارند و تگ <code>tag3</code> را ندارند</p>


```javascript
"segment": {
  "all": [
    {
      "name": "tags",
      "operator": "include",
      "value": ["tag1"]
    },
    {
      "name": "tags",
      "operator": "include",
      "value": ["tag2"]
    },
    {
      "name": "tags",
      "operator": "not_include",
      "value": ["tag3"]
    }
  ]
}
```
<p dir="rtl">سگمنت بالا برای کاربرانی ارسال میکند که هردو تگ <code>tag1</code> و <code>tag2</code> را دارند و تگ <code>tag3</code> را ندارند</p>
