### ISSUE TITLE
سوالات مربوط به نوتیفیکیشن

### ISSUE THREAD

**Issue by mehdi-mashayekhi** [chabokpush/chabok-php-demo#28]
سلام و وقت بخیر خدمت شما و همکاران محترمتون

چند تا سوال دارم
سوالات مربوط به ارسال وب پوش و نوتیفیکیشن هست

1:
آیا با ارسال یک اعلان (نوتیفیکیشن) بعد از اعلان دیگر بر روی دستگاه ها اعلان دیگری ظاهر میشود یا اعلان جدید بجای اعلان قبلی می آید؟

2:
چطور میتوان کاری کرد اعلانی که از قبل ارسال شده را بروز و یا جایگزین کرد با اعلانی جدید ؟

3:
اگر اعلان ها جدا جدا آورده میشوند ، پس حتما با کلیک روی یکی از اعلان ها اعلان های دیگر بسته خواهد شد درسته ؟

4:
اگر جواب سوال 3 مثبت هست ، پس در واقع اعلان های دیگه دقیقا بلا استفاده میشن چون شخص نمیتونه روشون کلیک کنه و وارد لینکشون بشه دیگه ؟

**Comment by mehdi-mashayekhi** [comment]
من الان تست گرفتم بصورت پیشفرض اعلان ها جدای از هم میان و با کلیک روی هر کدوم اعلان های دیگه باقی میمونند ، اما ما نیاز داریم تا بتونیم این شرایط را سفارشی کنیم مثلا تلگرام اگه میخواست به ازای هر پیام یدونه از این اعلان ها بزنه و بگه یه پیام جدید اومد که دیگه نمیشد ، مشکل دیگه ای هم که هست اگر یه منبع بیش از 100 نوتیفیکیشن در یک بازه ی زمانی ارسال کنه اتوماتیک اعلان هاش بلاک میشند

**Comment by behrad** [comment]
لطفن بفرمایید برای چه پلتفرمی مد نظر شماست؟
فکر میکنم روی همه پلتفرم ها میشه اعلان‌ها رو گروه بندی کرد

در مورد تعداد اعلان‌های ارسالیی به یک دستگاه، به نظرم خودتون خیلی راحت می تونید این رو مدیریت کنیید
در حال حاضر چابک محدودیتی روی ارسال به یک دستگاه اعمال نمیکنه

**Comment by mehdi-mashayekhi** [comment]
بسیارعالی ممنون از پاسخگویی
وب پوش روی مرورگرها هدف ما هستند

در رابطه با نحوه ی گروه بندی نوتیفیکیش و جایگزین کردن یا همون اپدیت کردن نوتیفیکیشن قبلی اطلاعات بفرمائید ممنون

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">برای گروه‌بندی نوتیفیکیشن‌ها در وب می‌تونین از کلید<code>tag</code> در <code>notification</code> استفاده کنید (این مورد در نسخه 1.0.2 اضافه می‌شود)</p>

<p dir="rtl">نوتیفیکشین‌هایی که مقدار <code>tag</code> یکسانی دارند در یک گروه قرار می‌گیرند.</p>

---
<h3 id="-" dir="rtl">تغییر</h3>
<p dir="rtl">کلید <code>tag</code> به <code>groupId</code> تغییر پیدا کرده است و جهت گروه‌بندی از کلید <code>groupId</code> استفاده کنید.</p>
<p dir="rtl"><a href="https://github.com/chabokpush/chabok-php-demo/issues/28#issuecomment-429808136">اطلاعات بیشتر در این قسمت</a></p>

**Comment by mehdi-mashayekhi** [comment]
سلام وقت بخیر نسخه جدید چه زمانی ارائه میشه

**Comment by amir-yaghoubi** [comment]
سلام
تا هفته بعد احتمالا یک نسخه خواهیم داد

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">@webtinax 
<a href="https://www.npmjs.com/package/chabokpush/v/1.0.2">نسخه ۱.۰.۲</a> منتشر شد.</p>
<p dir="rtl">در این نسخه نوتیفیکشن‌ها در حالت پیشفرض بر اساس <code>channel</code> گروه‌بندی می‌شوند.</p>
<p dir="rtl">جهت گروه‌بندی به صورت شخصی شده میتوانید کلید <code>groupId</code> را در قسمت <code>notification</code> فراهم آورید</p>
<p dir="rtl">نمونه:</p>


```json
{
  "user": "test_user",
  "channel": "default",
  "content": "example",
  "notification": {
    "title": "new message",
    "body": "notification grouping",
    "groupId": "news"
  }
}

```
<blockquote dir="rtl">
<p dir="rtl">نوتیفیکشن‌هایی که با <code>groupId: news</code> ارسال می‌شوند در یک گروه قرار میگیرند</p>
</blockquote>

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">من این issue رو می‌بندم، در صورتی که مشکلی در استفاده از این قابلیت داشتین دوباره باز کنین</p>
