### ISSUE TITLE
امکان ارسال یک محتوا به چندین کاربر

### ISSUE THREAD

**Issue by rasez** [chabokpush/chabok-php-demo#29]
سلام 
در جواب ریکوست به این ارور برمیخوریم
```
url : /push/toUsers
error: {"error":{"name":"Error","status":500,"message":"No Content Provided"}}
```
همه  پارامتر ها مثل داکیومنت مقداردهی میشوند

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">برای ارسال پوش، فراهم آوردن فیلد <code>content</code> اجباری می‌باشد.</p>
<p dir="rtl">خطای فوق با ارسال مقدار <code>content</code> رفع می‌شود</p>

```json
{
  "user": "USER_ID",
  "content": "sample",
  "channel": "default",
  "notification": {
    "title": "from chabok",
    "body": "Salam 😀"
  }
}
```

**Comment by rasez** [comment]
فیلد کانتنت هم توی پارامتر ها وجود داره

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">لطفا payload  خود را ارسال نمایید تا بیشتر بررسی کنم</p>

**Comment by rasez** [comment]
مشکل حل شد

**Comment by rasez** [comment]
من اگر بخوام به چند تا یوز همزمان بفرستم باید با کاما جدا کنم یوزر ها رو؟

**Comment by amir-yaghoubi** [comment]
<blockquote dir="rtl">
<p dir="rtl">من اگر بخوام به چند تا یوز همزمان بفرستم باید با کاما چدا کنم یوزر ها رو؟</p>
</blockquote>
<p dir="rtl">جهت ارسال به چند کاربر به وسیله‌ی <code>toUsers</code>، به ازای هر کاربر <code>payload</code> مورد نظر را ایجاد نموده و یک آرایه از <code>payload</code> های ایجاد شده به این <strong>API</strong> ارسال نمایید.</p>
<p dir="rtl">نمونه:</p>


```javascript
[
  {
    "user": "USER_1",
    "content": "sample",
    "channel": "default",
    "notification": {
      "title": "from chabok",
      "body": "Salam 😀"
  },
  {
    "user": "USER_2",
    "content": "sample",
    "channel": "default",
    "notification": {
      "title": "from chabok",
      "body": "Salam 😀"
    }
  }
  },
  {
    "user": "USER_3",
    "content": "sample",
    "channel": "default",
    "notification": {
      "title": "from chabok",
      "body": "Salam 😀"
    }
  }
]
```

**Comment by rasez** [comment]
با این روش که من اگه 30000 یوزر داشته باشم زنده نمیمونم

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">این روش برای ارسال به 30000 هزار کاربر قطعا نیست.
شما میتونین کاربران خودتون رو با استفاده از تگ‌ها و کانال‌ها و <a href="https://doc.chabokpush.com/rest-api/send-push.html#%D8%A7%D8%B1%D8%B3%D8%A7%D9%84-%D9%BE%D9%88%D8%B4-%D8%A7%D8%B2-%D8%B7%D8%B1%DB%8C%D9%82-%DA%AF%D8%B1%D9%88%D9%87%D8%A8%D9%86%D8%AF%DB%8C-%DA%A9%D8%A7%D8%B1%D8%A8%D8%B1%D8%A7%D9%86-segmented-push">سگمنت‌ها </a>دسته بندی کنین و بر اساس اینها و با استفاده از<a href="https://api.doc.chabokpush.com/#/push/push_byQuery"> <code>POST /push/byQuery</code></a> اقدام به ارسال پوش کنین.</p>
<p dir="rtl">برای مطالعه بیشتر میتونین به این قسمت از <a href="https://doc.chabokpush.com/rest-api/send-push.html">مستندات </a>مراجعه نمایید</p>

**Comment by behrad** [comment]
> با این روش که من اگه 30000 یوزر داشته باشم زنده نمیمونم

اگر استفاده از گروه بندی چابک و یا کانال‌ها براتون مقدور نیست و
احتمالن منظور شما این بوده که یک پیام رو به لیستی از یوزر‌آیدی‌ها بفرستید در این صورت این ای‌پی‌آی جدید رو براتون فراهم خواهیم کرد

**Comment by rasez** [comment]
بله منظورم همین بود ممنونم

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">@rasez 
قابلیت ارسال به لیستی از کاربران به <code>toUsers</code> اضافه شد.</p>
<p dir="rtl">برای استفاده از این قابلیت یک آرایه از نام‌های کاربری خود را در فیلد <code>users</code> قراردهید.</p>
<p dir="rtl">نمونه:</p>


```javascript
{
  "users": ["USER_1", "USER_2", "USER_3", "USER_4"],
  "content": "sample",
  "channel": "default",
  "notification": {
   "title": "from chabok",
   "body": "Salam 😀"
  }
}
```

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">من این issue رو می‌بندم، اگه همچنان سوالی در مورد استفاده از این API داشتید دوباره این issue را باز کنین.</p>
