### ISSUE TITLE
unregister یک سری از کاربران

### ISSUE THREAD

**Issue by amiriun** [chabokpush/chabok-php-demo#36]
سلام
وقت بخیر
میخواستم بدونم برای 
unregister
کردن یک سری از کاربران آیا 
api ای
وجود داره؟
ممنون

**Comment by behrad** [comment]
حذف کاربر عمومن از طریق خود متد داخل کلاینت انجام میشه

می تونم بپرسم مورد کاربرد (نیاز) شما برای حذف کاربر از سمت سرور چیه؟

**Comment by amiriun** [comment]
به دلیل اینکه کمتر از ۴کاراکتر در یوزر آی دی ساپورت نمیشود ، مجبور به تغییر یوزر آی دی ها شدیم و حالا میخوایم یوزر آیدی های قدیمی رو با جدید جایگزین کنیم

**Comment by behrad** [comment]
> به دلیل اینکه کمتر از ۴کاراکتر در یوزر آی دی ساپورت نمیشود

کافیه در سمت کلاینت یوزر‌آیدی ها رو به روش جدید رجیستر کنید
خود چابک براتون هندل میکنه
