### ISSUE TITLE
Check register API

### ISSUE THREAD

**Issue by amiriun** [chabokpush/chabok-php-demo#38]
سلام
وقت بخیر
از کدام 
API
میشه فهمید که یک یوزر آی دی خاص که میخوایم به اون نوتیفیکیشن بفرستیم تو چابک قبلا رجیستر شده یا نه؟

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">با استفاده از <a href="https://api.doc.chabokpush.com/#/installation/installation_fetchByUserId">fetchByUserId</a> شما میتونین لیست دستگاه‌های <code>userId</code> داده شده رو دریافت کنین. در صورتی که <code>userId</code> داده شده دستگاهی بر روی چابک نداشته باشد یک آرایه خالی بازگشت داده می‌شود</p>
