### ISSUE TITLE
Add tag to user and retrieve it 

### ISSUE THREAD

**Issue by asadijabar** [chabokpush/chabok-php-demo#4]
when I am calling the api https://sandbox.push.adpdigital.com/api//installations/addTag/user123/testTag
to add tage to user, api response is 
`
{
    "count": 0
}
`
what is this response ? and another one is when I wanna retrieve the list of tags :
https://sandbox.push.adpdigital.com/api/installations/tags
`
[
    "female",
    "xxx",
    "testTagFromApp",
    " ",
    "Hi3",
    "Man",
    "Test",
    "hiiiiii",
    "salam_Man",
    "Premium_User",
    "male",
    "VIP"
]
`
which i cannot find my new tag . why ?

**Comment by behrad** [comment]
> { "count": 0 }

This is number of devices for that userId which your tag is added. 0 means no device with userId `user123` exists, so your tag is not added to any device. 
Have you tested with any registered `userId`?



> [ "female", "xxx", "testTagFromApp", " ", "Hi3", "Man", "Test", "hiiiiii", "salam_Man", "Premium_User", "male", "VIP" ]

List of tags is returning all tags. Your tag is not added as I mentioned above. And this list is only the auto-generated tags for any account. (We may remove/empty our auto generated/test tags from accounts :) )

**Comment by asadijabar** [comment]
so how can i add users and tag with api ?

**Comment by behrad** [comment]
Users can be registered by client sdks (android, ios, js) not server sdk (php)
After you have a registered user, you can use the same api you mentioned :)
