### ISSUE TITLE
عدم ارسال پوش از طریق پست من

### ISSUE THREAD

**Issue by amirhosseinmajdi** [chabokpush/chabok-php-demo#41]
سلام وقتتون بخیر.
زمانی که بنده از طریق بخش مستندات سایت چابک اقدام به ارسال پوش میکنم به درستی ارسال میشه اما زمانی که میخوام از طریق پست من پوش رو ارسال کنم به مشکل مواجه میشم.لطفا بنده رو راهنمایی بفرمایید.
![chabok-issue](https://user-images.githubusercontent.com/36098869/50416541-7ecb0000-0836-11e9-838d-302e7622afc6.png)

![chabok-issue1](https://user-images.githubusercontent.com/36098869/50416549-8a1e2b80-0836-11e9-94a2-46c91fc1dd1e.png)

![chabok-issue2](https://user-images.githubusercontent.com/36098869/50416556-930efd00-0836-11e9-9677-599163eab4ca.png)

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">سلام</p>
<p dir="rtl">درباره عکس اول</p>
<p dir="rtl">فرمت <code>JSON</code> شما <code>valid</code> نیست (یک کاما ظاهرا اضافه هست)</p>
<p dir="rtl">عکس دوم و سوم لطفا درخواست را به صورت <code>form-data</code> ارسال نکنید و به صورت <code>raw/JSON</code> ارسال کنین</p>

<p dir="rtl">برای امتحان API ها میتونین از <a href="https://api.doc.chabokpush.com/#/push">swagger</a> استفاده کنین</p>

**Comment by amirhosseinmajdi** [comment]
سلام بنده کاما رو حذف کردم و ایندفعه اررور بد ریکویست به بنده میده
![chabok-issue3](https://user-images.githubusercontent.com/36098869/50417440-948ef400-083b-11e9-8d15-9e9e8f2a947a.png)

**Comment by amirhosseinmajdi** [comment]
مشکل حل شد نوع درخواست رو باید application/JSON قرار میدادم.ممنون

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">لطفا به صورت <code>raw/JSON</code> ارسال نمایید نه <code>Text</code></p>
<p dir="rtl">برای مطالعه بیشتر لطفا <a href="https://doc.chabokpush.com/rest-api/send-push-notification.html">بخش مستندات</a> را مطالعه نمایید</p>
