### ISSUE TITLE
ارسال پوش همزمان به چند یوزر

### ISSUE THREAD

**Issue by amirhosseinmajdi** [chabokpush/chabok-php-demo#42]
سلام وقتتون بخیر.
ما میخوایم از طریق پوش درخواست ارسال کنیم به سه یوزر به صورت آرایه
```
{
  "user": ["user1","user2","user3"],
  "content": "message",
  "data": {},
  "trackId": "string",
  "inApp": false,
  "live": false,
  "autoNotify": false,
  "useAsAlert": false,
  "alertText": "string",
  "ttl": 0,
  "clientId": "string",
  "silent": false
}
```
این آرایه ما در پست من هست و در ریسپانس هم آیدی رو بر میگردونه به این معنی که ارسال شده ولی پوش دریافت نمیشه تو اپ.اما وقتی با تک یوزر به صورت استرینگ امتحان میکنم جواب میده و پوش دریافت میشه.

**Comment by amir-yaghoubi** [comment]
<p dir="rtl">جهت ارسال به آرایه ای از کاربران همان طور که در این <a href="https://doc.chabokpush.com/rest-api/send-chabok-message.html">قسمت از مستندات</a> به مطرح شده باید آن را در کلید <code>users</code>قرار دهید.</p>
<p dir="rtl">در نتیجه:</p>

```
{
  "users": ["user1","user2","user3"],
  "content": "message",
  "data": {},
  "trackId": "string",
  "inApp": false,
  "live": false,
  "autoNotify": false,
  "useAsAlert": false,
  "alertText": "string",
  "ttl": 0,
  "clientId": "string",
  "silent": false
}
```
