### ISSUE TITLE
ارسال notification

### ISSUE THREAD

**Issue by hoseinjamshidi** [chabokpush/chabok-php-demo#45]
<p dir="rtl">سلام وقت بخر برای ارسال نوتیفیکیشن برای یک کاربر خاص با استفاده از toUsers بحای &quot;user&quot;باید چه مقداری ارسال بشه؟</p>

**Comment by Husseinhj** [comment]
<p dir="rtl">لطفا <a href="https://doc.chabokpush.com/rest-api/send-push.html#%D9%85%D8%AB%D8%A7%D9%84-%D8%A7%D8%B1%D8%B3%D8%A7%D9%84-%D8%B4%D8%AE%D8%B5%DB%8C-%D9%BE%DB%8C%D8%A7%D9%85-%DA%86%D8%A7%D8%A8%DA%A9-%D8%A8%D9%87-%DB%8C%DA%A9-%DA%A9%D8%A7%D8%B1%D8%A8%D8%B1">این بخش از مستندات</a> رو مطالعه بفرمایید</p>
<p dir="rtl">برای مثال شما می‌خواین به کاربر userId_1234 پوش ارسال کنین:</p>
<pre><code>curl -X POST \
&quot;https://sandbox.push.adpdigital.com/api/push/toUsers?access_token=&lt;ACCESS_TOKEN&gt;&quot; \
-H &quot;accept: application/json&quot; \
-H &quot;Content-Type: application/json&quot; \
-d &quot;{ \&quot;user\&quot;: \&quot;userId_1234\&quot;, \&quot;content\&quot;: \&quot;پرواز شما دچار نیم ساعت تاخیر شده است.\&quot;, \&quot;useAsAlert\&quot;: true}&quot;</code></pre>

**Comment by hoseinjamshidi** [comment]
ممنون از شما
