### ISSUE TITLE
نمایش عنوان

### ISSUE THREAD

**Issue by hoseinjamshidi** [chabokpush/chabok-php-demo#46]
سلام وقت بخیر
نوتیفیکیشن با متد/push/toUsers ارسال میشود
برای نمایش عنوان در نوتیفیکیشن ارسالی باید از چه روشی استفاده کنیم؟؟؟

**Comment by Husseinhj** [comment]
<p dir="rtl"><a href="https://doc.chabokpush.com/rest-api/send-push.html#%D8%A7%D8%B1%D8%B3%D8%A7%D9%84-%D8%B4%D8%AE%D8%B5%DB%8C">لطفا مستندات api رو مطالعه بفرمایید</a></p>
<p dir="rtl">تصویر مستندات:
<img src="https://user-images.githubusercontent.com/27139702/62003456-686a8700-b12c-11e9-8452-add5d4ee5707.png" alt="image"></p>
<p dir="rtl">curl :</p>
<pre><code>curl -X POST &quot;https://sandbox.push.adpdigital.com/api/push/toUsers?access_token=&lt;ACCESS_TOKEN&gt;&quot; -H &quot;accept: application/json&quot; -H &quot;Content-Type: application/json&quot; \
-d &quot;{ \&quot;user\&quot;: \&quot;USER_1\&quot;, \&quot;content\&quot;: \&quot;سفارش شما با موفقیت ثبت شد\&quot;, \&quot;channel\&quot;: \&quot;default\&quot;, \&quot;notification\&quot;: { \&quot;title\&quot;: \&quot;چابک\&quot;, \&quot;body\&quot;: \&quot;سفارش ثبت شد\&quot; } }&quot;</code></pre>

**Comment by hoseinjamshidi** [comment]
<p dir="rtl">این json ارسالی به چابک میباشد</p>
<pre><code class="language-json">&quot;{\&quot;user\&quot;:\&quot;09412a69-5323-4661-bde8-3780519695f7\&quot;,\&quot;channel\&quot;:\&quot;default\&quot;,\&quot;content\&quot;:\&quot;کاربر گرامی،اکانت کاربری شما توسط پشتیبان مشیر فعال شد\&quot;,\&quot;data\&quot;:{},\&quot;trackId\&quot;:null,\&quot;inApp\&quot;:false,\&quot;live\&quot;:false,\&quot;autoNotify\&quot;:false,\&quot;useAsAlert\&quot;:true,\&quot;alertText\&quot;:null,\&quot;ttl\&quot;:0.0,\&quot;fallback\&quot;:null,\&quot;clientId\&quot;:null,\&quot;notification\&quot;:{\&quot;title\&quot;:\&quot;اعلان انبلاک شدن\&quot;,\&quot;body\&quot;:\&quot;کاربر گرامی،اکانت کاربری شما توسط پشتیبان مشیر فعال شد\&quot;,\&quot;groupId\&quot;:null,\&quot;icon\&quot;:null,\&quot;sound\&quot;:null,\&quot;clickUrl\&quot;:null,\&quot;ledColor\&quot;:null,\&quot;smallIcon\&quot;:null,\&quot;actions\&quot;:{\&quot;id\&quot;:\&quot;string\&quot;,\&quot;title\&quot;:\&quot;اعلان انبلاک شدن\&quot;,\&quot;options\&quot;:0.0,\&quot;icon\&quot;:null},\&quot;mediaType\&quot;:null,\&quot;mediaUrl\&quot;:null,\&quot;contentAvailable\&quot;:false,\&quot;mutableContent\&quot;:false,\&quot;category\&quot;:null},\&quot;silent\&quot;:false}&quot;</code></pre>
<p dir="rtl">اما عنوان نمایش داده نمیشود</p>

**Comment by Husseinhj** [comment]
<p dir="rtl">روی چه پلتفرمی تست می‌کنین؟ (اندروید یا iOS)</p>
<p dir="rtl">آیا اقدام به شخصی‌سازی نوتیفیکیشن توی کد <a href="https://doc.chabokpush.com/android/push-notification.html#%D8%B4%D8%AE%D8%B5%DB%8C%D8%B3%D8%A7%D8%B2%DB%8C-%D9%86%D9%85%D8%A7%DB%8C%D8%B4-%D9%88-%DA%A9%D9%84%DB%8C%DA%A9-%D8%B1%D9%88%DB%8C-%D8%A7%D8%B9%D9%84%D8%A7%D9%86">اندروید</a> یا <a href="https://doc.chabokpush.com/ios/push-notification.html#%D8%B4%D8%AE%D8%B5%DB%8C%D8%B3%D8%A7%D8%B2%DB%8C-%D9%86%D9%85%D8%A7%DB%8C%D8%B4-%D8%A7%D8%B9%D9%84%D8%A7%D9%86">iOS</a> می‌کنید؟</p>
<blockquote dir="rtl">
<p dir="rtl"><code>نکته</code>: لطفا کلیدهایی رو سمت چابک ارسال کنید که لازم هست و مقادیر null رو از payload حذف کنید.

<a href="https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_NullValueHandling.htm">NullValueHandling در Newtonsoft.Json</a> 
<a href="https://github.com/restsharp/RestSharp/wiki/Usage-way">NullValueHandling در RestSharp</a></p>
</blockquote>

**Comment by hoseinjamshidi** [comment]
<p dir="rtl">روی پلتفرم اندروید تست میشه
برنامه نویس اندرود اعالم کردن که مقدار title در دیوایس مقصد null دریافت میشود</p>

**Comment by Husseinhj** [comment]
<p dir="rtl">کلید <code>actions</code> در <code>notification</code> باید به صورت آرایه باشه. </p>
<p dir="rtl"> لطفا کلیدها رو به درستی وارد کنید و مقداری که لازم ندارید رو از پیلود حذف کنید.</p>
<pre><code>{
  &quot;user&quot;: &quot;09412a69-5323-4661-bde8-3780519695f7&quot;,
  &quot;channel&quot;: &quot;default&quot;,
  &quot;content&quot;: &quot;کاربر گرامی،اکانت کاربری شما توسط پشتیبان مشیر فعال شد&quot;,
  &quot;data&quot;: {},
  &quot;trackId&quot;: null,
  &quot;inApp&quot;: false,
  &quot;live&quot;: false,
  &quot;autoNotify&quot;: false,
  &quot;useAsAlert&quot;: true,
  &quot;alertText&quot;: null,
  &quot;ttl&quot;: 0,
  &quot;fallback&quot;: null,
  &quot;clientId&quot;: null,
  &quot;notification&quot;: {
    &quot;title&quot;: &quot;اعلان انبلاک شدن&quot;,
    &quot;body&quot;: &quot;کاربر گرامی،اکانت کاربری شما توسط پشتیبان مشیر فعال شد&quot;,
    &quot;groupId&quot;: null,
    &quot;icon&quot;: null,
    &quot;sound&quot;: null,
    &quot;clickUrl&quot;: null,
    &quot;ledColor&quot;: null,
    &quot;smallIcon&quot;: null,
    &quot;actions&quot;: {
      &quot;id&quot;: &quot;string&quot;,
      &quot;title&quot;: &quot;اعلان انبلاک شدن&quot;,
      &quot;options&quot;: 0,
      &quot;icon&quot;: null
    },
    &quot;mediaType&quot;: null,
    &quot;mediaUrl&quot;: null,
    &quot;contentAvailable&quot;: false,
    &quot;mutableContent&quot;: false,
    &quot;category&quot;: null
  },
  &quot;silent&quot;: false
}</code></pre><p dir="rtl">پیلودی که به چابک برای این پوش ارسال می‌کنید باید به شکل زیر باشد:</p>
<pre><code>{
  &quot;user&quot;: &quot;09412a69-5323-4661-bde8-3780519695f7&quot;,
  &quot;channel&quot;: &quot;default&quot;,
  &quot;content&quot;: &quot;کاربر گرامی،اکانت کاربری شما توسط پشتیبان مشیر فعال شد&quot;,
  &quot;useAsAlert&quot;: true,
  &quot;notification&quot;: {
    &quot;title&quot;: &quot;اعلان انبلاک شدن&quot;,
    &quot;body&quot;: &quot;کاربر گرامی،اکانت کاربری شما توسط پشتیبان مشیر فعال شد&quot;,
    &quot;actions&quot;: [{
      &quot;id&quot;: &quot;string&quot;,
      &quot;title&quot;: &quot;اعلان انبلاک شدن&quot;,
      &quot;options&quot;: 0
    }]
  }
}</code></pre><p>curl:</p>
<pre><code>curl -X POST \
  https://sandbox.push.adpdigital.com/api/push/toUsers \
  -H &#39;Content-Type: application/json&#39; \
  -H &#39;X-Access-Token: &lt;ACCESS_TOKEN&gt;&#39; \
  -d &#39;{
  &quot;user&quot;: &quot;09412a69-5323-4661-bde8-3780519695f7&quot;,
  &quot;channel&quot;: &quot;default&quot;,
  &quot;content&quot;: &quot;کاربر گرامی،اکانت کاربری شما توسط پشتیبان مشیر فعال شد&quot;,
  &quot;useAsAlert&quot;: true,
  &quot;notification&quot;: {
    &quot;title&quot;: &quot;اعلان انبلاک شدن&quot;,
    &quot;body&quot;: &quot;کاربر گرامی،اکانت کاربری شما توسط پشتیبان مشیر فعال شد&quot;,
    &quot;actions&quot;: [{
      &quot;id&quot;: &quot;string&quot;,
      &quot;title&quot;: &quot;اعلان انبلاک شدن&quot;,
      &quot;options&quot;: 0
    }]
  }
}&#39;</code></pre>

**Comment by hoseinjamshidi** [comment]
ممنون

**Comment by hoseinjamshidi** [comment]
سلام مجدد
برای ارسال بخش actions از روش زیر استفاده شده اما با ارور روبرو شدیم
                    NotificationActions[] action = new NotificationActions[1];
                    action[0] = new  NotificationActions
                    {
                        id = specificUsers.notification.actions.id,
                        title = specificUsers.notification.actions.title,
                        options = 0
                    };

                    myObject.NotificationPayload.actions = action;

**Comment by hoseinjamshidi** [comment]
مشکل حل شد ممنون
